# Generated by Django 5.1.1 on 2024-10-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
    ]
