# Generated by Django 5.1.1 on 2024-10-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_deliveryaddress_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line2',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
