# Generated by Django 5.1.1 on 2024-10-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='state',
            field=models.CharField(choices=[('placing', 'Placing'), ('placed', 'Placed')], default='placing', max_length=20),
        ),
    ]
