# Generated by Django 5.1.1 on 2024-10-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
