# Generated by Django 5.1.1 on 2024-10-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
